init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Bootstrap
        Progress "Downloading external software"
        md C:\Rextsoft
        Invoke-WebRequest http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local320.zip -OutFile "C:\Rextsoft\local320.zip"
        7z x C:\Rextsoft\local320.zip -oC:\Rextsoft -r
        sed "s#^LOCAL_SOFT = d:/RCompile/r-compiling/local/local320#LOCAL_SOFT = C:/Rextsoft#" E:\R\etc\i386\Makeconf > E:\R\etc\i386\Makeconf_tmp
        Copy-Item E:\R\etc\i386\Makeconf_tmp -Destination E:\R\etc\i386\Makeconf -Force
        sed "s#^LOCAL_SOFT = d:/RCompile/r-compiling/local/local320#LOCAL_SOFT = C:/Rextsoft#" E:\R\etc\x64\Makeconf > E:\R\etc\x64\Makeconf_tmp
        Copy-Item E:\R\etc\x64\Makeconf_tmp -Destination E:\R\etc\x64\Makeconf -Force

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

notifications:
  - provider: Slack
    auth_token:
      secure: Da1t3XpyPl/xPpY98Ay83DJc6J0p8jsdu5GB3dMVBypGXGSss6D/4rzHdCmN+xNu
    channel: builds
